<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitc270454f357ff1e3422c1ba6a4b48250
{
    public static $files = array (
        '71715d4c8778517b225fa14ed4e16b10' => __DIR__ . '/../..' . '/.includes/constants.php.inc',
        '5b7ea1064199cf668e4d182483228260' => __DIR__ . '/../..' . '/.includes/functions.php.inc',
    );

    public static $prefixLengthsPsr4 = array (
        'Q' => 
        array (
            'Qithub\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Qithub\\' => 
        array (
            0 => __DIR__ . '/..' . '/qithub/core/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitc270454f357ff1e3422c1ba6a4b48250::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitc270454f357ff1e3422c1ba6a4b48250::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
